[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "Polynomial-Fitter"
dynamic = ["version"]
description = "Polynomial-Fitter"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.5",
    "openpyxl>=3.1.5",
    "pygal>=3.1.0",
    "rich>=15.0.0",
    "rich-argparse>=1.8.0",
    "scipy>=1.17.1",
]

[project.urls]
"Homepage" = "https://github.com/YanMing-lxb/Polynomial-Fitter"
"Bug Tracker" = "https://github.com/YanMing-lxb/Polynomial-Fitter/issues"

[project.scripts]
polyfit = "src.main:main"

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = true

[dependency-groups]
dev = [
    "pyinstaller>=6.20.0",
]

[tool.setuptools.dynamic]
version = {attr = "src.version.__version__"}